apiVersion: v1
kind: Service
metadata:
    name: svc-stackstudentsapiprod
    labels:
        product: stackstudentsapiprod
spec:
    selector:
        app: app-stackstudentsapiprod
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: dep-stackstudentsapiprod
spec:
    replicas: 1
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: app-stackstudentsapiprod
        spec:
            containers:
            - image: dockerapiatc.azurecr.io/stackstudentsdevopsapi:__Build.BuildId__
              imagePullPolicy: IfNotPresent
              name: stackstudentsapiprod
              ports:
              - containerPort: 80
              env:
              - name: ASPNETCORE_ENVIRONMENT
                value: "Production"
            imagePullSecrets:
            - name: regsecret